name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Galleries"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Deployment for GitHub Pages
        run: |
          # Ensure we are working on the main branch
          git checkout main

          # Make sure the repository is up to date with the remote
          git pull origin main

          # Clean the old files before copying new ones
          rm -rf ./*

          # Explicitly check the galleries folder exists at root and copy its contents
          if [ -d "./galleries" ]; then
            cp -r ./galleries/* ./  # Ensure we use the relative path to the root of the repo
          else
            echo "No galleries directory found."
          fi

          # Check and copy photos if available
          if [ -d "./photos" ]; then
            cp -r ./photos ./  # Copy photos to root if they exist
          fi

          # Check and copy style.css if it exists
          if [ -f "./style.css" ]; then
            cp ./style.css ./  # Copy CSS file to root if it exists
          fi

          # Check and copy scripts if available
          if [ -d "./scripts" ]; then
            cp -r ./scripts ./  # Copy scripts if they exist
          fi
          
          # Commit the changes (if any)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add .

          # Commit only if there are changes
          git diff-index --quiet HEAD || git commit -m "Deploy generated galleries"

          # Push the changes to the main branch
          git push origin main

      - name: Clean up (optional)
        run: |
          # Clean up after deployment (optional)
          rm -rf galleries/*
          rm -rf photos/*
