name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Galleries"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed, based on your project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (if necessary)
        run: npm install  # Optional, if you need to install dependencies for building the page

      - name: Build the site (if needed)
        run: npm run build  # Skip this step if you don't need to build anything

      - name: Prepare Deployment for GitHub Pages
        run: |
          # Ensure we are working on the main branch
          git checkout main

          # Make sure the repository is up to date with the remote
          git pull origin main

          # Clean the old files before copying new ones
          rm -rf ./*

          # Copy over the generated gallery HTML files and other assets (like images, CSS, etc.)
          cp -r galleries/* ./
          cp -r photos ./  # Assuming photos need to be copied as well
          cp -r style.css ./  # Ensure the CSS is included if needed
          cp -r scripts ./  # Include JS scripts if applicable
          
          # Commit the changes (if any)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add .

          # Commit the changes only if there are any updates
          git diff-index --quiet HEAD || git commit -m "Deploy generated galleries"

          # Push the changes to the main branch
          git push origin main

      - name: Clean up (optional)
        run: |
          # Clean up after deployment (optional, based on your project setup)
          rm -rf galleries/*
          rm -rf photos/*
