name: Deploy Pages to GitHub

on:
  workflow_run:
    workflows: ["Generate Galleries"]  # Wait for the "Generate Galleries" workflow to complete
    types:
      - completed

permissions:
  contents: write  # Allow writing to the repository (important for deploying)

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}  # Prevents deployment overlap

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to ensure you're on the correct branch
      - name: Checkout repository
        uses: actions/checkout@v4

      # List files in the repository for debugging purposes
      - name: List files in the repo (Debugging)
        run: |
          ls -la

      # Check if there are changes before attempting to commit
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"

      # Commit changes if necessary
      - name: Commit changes
        if: steps.check_changes.outputs.stdout == 'Changes detected'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy new content to GitHub Pages"
          git push

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Deploy the root directory
          branch: gh-pages  # Deploy to the 'gh-pages' branch (or 'main' if you're using that)

