name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Galleries"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if applicable, based on your project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (if necessary)
        run: npm install  # Optional, if you need to install dependencies for building the page

      - name: Build the site (if needed)
        run: npm run build  # Skip this step if you don't need to build anything

      - name: Prepare GitHub Pages Deployment
        run: |
          # Ensure we have the latest gh-pages branch
          git fetch origin

          # Create gh-pages branch if it doesn't exist yet
          git checkout --orphan gh-pages || git checkout gh-pages

          # Clean the gh-pages branch (remove all files before deploying)
          rm -rf ./*

          # Copy over the generated gallery HTML files and assets (if any)
          cp -r galleries/* ./
          cp -r photos ./  # Assuming photos folder needs to be copied as well

          # Commit the changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Add all changes (files generated from galleries)
          git add .

          # Commit the changes (if there are any)
          git diff-index --quiet HEAD || git commit -m "Deploy generated galleries"

          # Force push to the gh-pages branch
          git push --force origin gh-pages

      - name: Clean up
        run: |
          # Optionally clean up after deployment
          rm -rf galleries/*
          rm -rf photos/*
