name: Deploy Pages to GitHub

on:
  workflow_run:
    workflows: ["Generate Galleries"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy directly to GitHub Pages (from the 'main' branch)
      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4
        with:
          branch: main    # Specify 'main' branch
          folder: .       # Deploy the root folder
