name: Update Timeline

on:
  push:
    branches:
      - main  # Adjust to your default branch if it's different

jobs:
  update-timeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if needed for script execution)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version as per your need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm init -y
          npm install fs-extra

      # Step 4: Create the index.html and update timeline
      - name: Generate and Update Timeline
        run: |
          const fs = require('fs');
          const path = require('path');
          const timelineDir = './timeline';
          const indexPath = './index.html';

          const generateTimeline = () => {
            const files = fs.readdirSync(timelineDir);
            let timelineData = [];

            // Read all txt files from the timeline folder
            files.forEach((file, index) => {
              if (path.extname(file) === '.txt') {
                const year = path.basename(file, '.txt'); // Extract year from file name
                const content = fs.readFileSync(path.join(timelineDir, file), 'utf8');
                timelineData.push({
                  year,
                  content,
                  side: index % 2 === 0 ? 'left' : 'right', // Alternating sides
                });
              }
            });

            // Read the existing index.html template
            let htmlContent = `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>GXBTX</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/style.css" />
  </head>
  <body id="top">
    <div id="header"></div>
    <div class="main">
      <div class="timeline">
    `;

            // Build the timeline section
            timelineData.forEach(item => {
              htmlContent += `
        <div class="container ${item.side}">
          <div class="content">
            <h2>${item.year}</h2>
            <p>${item.content}</p>
          </div>
        </div>
              `;
            });

            // Close the timeline section
            htmlContent += `
      </div>
      <a href="#top">Back to Top</a>
    </div>

    <div id="footer"></div>
    <script src="/scripts/make_header_footer.js" async defer></script>
  </body>
</html>
            `;

            // Write the updated HTML back to index.html
            fs.writeFileSync(indexPath, htmlContent);
          };

          // Execute the timeline generation
          generateTimeline();

      # Step 5: Commit changes if index.html was modified
      - name: Commit updated index.html
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add index.html
          git commit -m "Update timeline"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
